# Note this file is only for local development

version: "3.3"

# docker ps - list all running containers
# docker-machine ip default -> shows docker's ip address

services:
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "tiptracker"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db-vol:/var/lib/mysql
  mongo:
    container_name: tiptracker_mongo
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mysql-db-vol:
  mongodb:
  mongodb_config:
